all:
	@echo "use 'make a1' to run Q1a1"
	@echo "use 'make a2' to run Q1a2"
	@echo "use 'make b' to run Q1b"

a1:
	gcc -o 1a1 1a1.c
	./1a1
	rm -f 1a1
a2:
	gcc -o 1a2 1a2.c
	./1a2
	rm -f 1a2

b:
	gcc -o 1b 1b.c
	./1b
	rm -f 1b